export const STORE_DESEQ2_STATISTICS = 'store_deseq2_statistics'
export const EXTEND_FILE_LIST = 'extend_file_list'
export const REGISTER_CONDITION = 'register_condition'
export const SEARCH_REGEX = 'search_regex'
export const STORE_COUNT_TABLE = 'store_count_table'
export const SET_SUBDGE = 'set_subDGE'
