export const ADD_DATA = 'add_data'
export const ADD_FILE = 'add_file'
export const ADD_CONDITION = 'add_condition'
export const ADD_COUNT_DATA = 'add_count_data'
export const ADD_SEQRUN_MAPPING = 'add_seqrun_mapping'
export const ADD_SUBSET_DGE = 'add_subset_dge'
export const SWITCH_DGE = 'switch_dge'
